# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

LIMITE_SEGURANCA = 10000.0





v1 = float(input("Venda 1: "))

v2 = float(input("Venda 2: "))

v3 = float(input("Venda 3: "))



def analisar_vendas(v1, v2, v3):

  global LIMITE_SEGURANCA



  media = (v1 + v2 + v3) / 3

  print("Média:", media)



  if media > LIMITE_SEGURANCA:

    print("SISTEMA EM QUARENTENA")



  if v1 > media * 5 or v2 > media * 5 or v3 > media * 5:

    print("REVISÃO MANUAL")



  print("Tipo v1:", type(v1))

  print("Tipo média:", type(media))

  print("Tipo limite:", type(LIMITE_SEGURANCA))



analisar_vendas(v1, v2, v3)